name = "reserv-keion"
main = "src/index.ts"
compatibility_date = "2025-03-21"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "2d74246671e144c6a91b43801cfa5b28"